### ISSUE TITLE
CRA2 script error on build, 3.0.0 changes not applying

### ISSUE THREAD

**Issue by bdefore** [jonathantneal/react-app-rewire-postcss#7] opened 2018-10-04 15:21 UTC
I believe the changes in https://github.com/csstools/react-app-rewire-postcss/pull/6 for CRA2 support are incomplete. There are two issues:

- running `yarn run build` causes a script error as its webpack configuration is subtly changed from dev, and `filterPostCSSLoader(rule.oneOf)` does not find the loader it's looking for
- in the test repo pull request to fix https://github.com/csstools/react-app-rewire-postcss/issues/5 the direct import of variables.css here (https://github.com/bdefore/rewired-custom-properties-cra2/pull/1/files#diff-1fdf421c05c1140f6d71444ea2b27638R4) may have deceived, since it does apply css variables which suits the need of the original request, but the rewire of postcss-env applies the options but not the plugin configuration which actually pulls in variables.css. if the import of variables.css in App.js is removed, the test case is still broken. i've updated the repo without the import to verify this.

i forked and created a branch (https://github.com/bdefore/react-app-rewire-postcss/blob/cra2-fix/index.js) that attempted to fix both cases. it does the following:

- pass `env` to the `rewirePostcss` call in config overrides (this would be a breaking api change since options moves to the third parameter, but is more conventional with other rewire plugins)
- based on `env` being `production` or not, uses a different matching algorithm to find the loader/rule
- mutates that loader/rule with the given options

this finds the loader and applies options for both production and development builds, however the result is the same: custom properties are not applied, and i believe this may be because it's not applying the plugins node properly that actually brings in the effects of `postcssPresetEnv`. perhaps you'd be more familiar with how to get this across the line @jonathantneal ?

**Comment by jonathantneal** [comment] 2018-10-04 15:35
- I can’t test for yarn. I just don’t have the hours.
- `variables.css` is used by modern browsers to support true Custom Properties, while PostCSS Preset Env uses it to provide the fallback color when Custom Properties are not supported. I left you a note about that works in the PR.


I’ll review a PR if you think this app can be improved, but I verified it working on that repo.

**Comment by bdefore** [comment] 2018-10-04 15:44
The behavior I'm seeing is the same for npm or yarn.

Which browser did do you verify on? From the latest on the test repo, `npm run build` fails with the error `TypeError: Cannot read property 'filter' of undefined` and `npm start` does not render the third test case green on the latest version of Chrome.

I've held off on a PR since my reimplementation is incomplete.

**Comment by bdefore** [comment] 2018-10-04 15:49
Maybe I'm misunderstanding: does the custom properties fallback not get applied if the browser supports them? In which case it would be expected and desired that removing the direct import of variables.css removes the style.

**Comment by jonathantneal** [comment] 2018-10-04 15:54
@bdefore, if you remove `variables.css` from `index.js`, modern browsers will never see the color because they support the declaration using `var()` — thus ignoring the fallback declaration — but they don’t know the value of the Custom Property being referenced.

**Comment by bdefore** [comment] 2018-10-04 16:03
Ah ok. Makes sense. Then this issue would mainly come down to addressing the production build failure. And it's possible my branch already solves that.

**Comment by alexdevero** [comment] 2018-10-06 08:04
The same issue with broken build script:
```
const filterPostCSSLoader = array => array.filter(object => JSON.stringify(object).includes('
postcss-loader'));                                                                           
                                           ^                                                 
                                                                                             
TypeError: Cannot read property 'filter' of undefined                                        
    at filterPostCSSLoader (c:\temp\node_modules\react-app-rewire-postcss\index.cjs.js:19:44)                               
    at filterPostCSSLoader.forEach.oneOf (c:\temp\node_modules\react-app-rewire-postcss\index.cjs.js:7:7)                   
    at Array.forEach (<anonymous>)                                                           
    at filterPostCSSLoader.forEach.rule (c:\temp\node_modules\react-app-rewire-postcss\index.cjs.js:6:37)                   
    at Array.forEach (<anonymous>)                                                           
    at index (c:\temp\node_modules\react-app-rewire-postcss\index.cjs.js:5:44)                                              
    at Object.module.exports.config [as webpack] (c:\temp\config-overrides.js:2:40)                                         
    at Object.<anonymous> (c:\temp\node_modules\react-app-rewired\scripts\build.js:11:13)                                   
    at Module._compile (internal/modules/cjs/loader.js:689:30)                               
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                 
    at Module.load (internal/modules/cjs/loader.js:599:32)                                   
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                 
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)                          
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)                       
    at startup (internal/bootstrap/node.js:279:19)                                           
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)                                
npm ERR! code ELIFECYCLE                                                                     
npm ERR! errno 1                                                                             
```

**Comment by alexdevero** [comment] 2018-10-09 09:03
React-app-rewire-postcss v2.0.0 works like a charm. Is there any progress on this issue?

`package.json` for failing build script:
```
{
    "name": "my-project",
    "version": "0.0.1",
    "private": false,
    "browserslist": [
        "> 4%",
        "Chrome >= 64",
        "Edge > 13",
        "Firefox >= 59",
        "IE 11",
        "last 4 versions",
        "Safari >= 9"
    ],
    "dependencies": {
        "react-dom": "^16.5.2",
        "react-router-dom": "^4.3.1",
        "react-scripts-ts": "3.1.0"
    },
    "scripts": {
        "build": "react-app-rewired build --scripts-version react-scripts-ts",
        "eject": "react-scripts-ts eject",
        "lint": "tslint -c tslint.json 'src/**/*.ts', 'src/**/*.tsx' -o tslint.log",
        "preview": "npm run build && serve -s build",
        "start": "sh -ac '. ./.env.development;' && react-app-rewired start --scripts-version react-scripts-ts",
        "test": "react-scripts-ts test --env=jsdom"
    },
    "devDependencies": {
        "@types/node": "^10.9.4",
        "@types/react-dom": "16.0.7",
        "postcss-extend": "^1.0.5",
        "postcss-import": "^12.0.0",
        "postcss-nesting": "^7.0.0",
        "postcss-preset-env": "^6.0.10",
        "postcss-pxtorem": "^4.0.1",
        "react-app-rewire-postcss": "^3.0.0",
        "react-app-rewired": "^1.6.2",
        "serve": "^10.0.2",
        "typescript": "^3.0.3"
    }
}
```

`config-overrides.js` for failing build script:
```
module.exports = config => require('react-app-rewire-postcss')(config, {
    plugins() {
        return [
            require('postcss-import')(),
            require('postcss-extend')(),
            require('postcss-nesting')(),
            require('postcss-preset-env')({
                stage: 3
            }),
            require('postcss-pxtorem')({
                mediaQuery: false,
                minPixelValue: 0,
                propWhiteList: [],
                replace: true,
                rootValue: 16,
                selectorBlackList: ['html'],
                unitPrecision: 5
            }),
            require('cssnano')()
        ]
    }
})
```

**Comment by jonathantneal** [comment] 2018-10-09 11:26
At this point, it’s just the `build` that is not working, yes? @bdefore, did you have a solution?

**Comment by jonathantneal** [comment] 2018-10-09 12:13
I looked into the issue and found a solution. It has been fixed in v3.0.1.

**Comment by jonathantneal** [comment] 2018-10-09 12:13
Fixed in https://github.com/csstools/react-app-rewire-postcss/commit/88c9da5b1d24b7ba0dade80b2d0b14964c86c356

**Closed as completed by jonathantneal** 2018-10-09 12:13 UTC

**Comment by alexdevero** [comment] 2018-10-09 12:34
@jonathantneal I can confirm that v3.0.1 **works like a charm**. Good job! Thank you.

**Comment by bdefore** [comment] 2018-10-09 14:36
confirmed here too. thanks.
